/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ship_light.gltf --types 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Billboard, Float, Text, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody, RapierRigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
	nodes: {
		ship_light_8angles_1: THREE.Mesh;
		ship_light_8angles_2: THREE.Mesh;
		ship_light_8angles_3: THREE.Mesh;
		ship_light_8angles_4: THREE.Mesh;
		ship_light_8angles_5: THREE.Mesh;
		ship_light_8angles_6: THREE.Mesh;
		cannon_front_1_1: THREE.Mesh;
		cannon_front_1_2: THREE.Mesh;
		cannon_front_1_3: THREE.Mesh;
		cannon_left_1_1: THREE.Mesh;
		cannon_left_1_2: THREE.Mesh;
		cannon_left_1_3: THREE.Mesh;
		cannon_left_1_8: THREE.Mesh;
		cannon_left_1_9: THREE.Mesh;
		cannon_right_1_1: THREE.Mesh;
		sail_back_1_1: THREE.Mesh;
		sail_back_1_2: THREE.Mesh;
		sail_front_1_1: THREE.Mesh;
		sail_front_1_2: THREE.Mesh;
		sail_middle_1_1: THREE.Mesh;
		sail_middle_1_2: THREE.Mesh;
		steering_1_1: THREE.Mesh;
		steering_1_2: THREE.Mesh;
	};
	materials: {
		wood: THREE.MeshStandardMaterial;
		woodDark: THREE.MeshStandardMaterial;
		iron: THREE.MeshStandardMaterial;
		window: THREE.MeshStandardMaterial;
		textile: THREE.MeshStandardMaterial;
		_defaultMat: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

type ContextType = Record<
	string,
	React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export const ShipLight = (props: JSX.IntrinsicElements["group"]) => {
	const { nodes, materials } = useGLTF("/models/ship_light.gltf") as GLTFResult;

	const rb = useRef<RapierRigidBody>(null);
	const floatRef = useRef<THREE.Group<THREE.Object3DEventMap>>(null);
	const shipLightRef = useRef<THREE.Group<THREE.Object3DEventMap>>(null);

	return (
		<group {...props} dispose={null} ref={shipLightRef}>
			<Float
				ref={floatRef}
				speed={5}
				rotationIntensity={0.2}
				floatingRange={[0, 0.3]}
			>
				<Billboard position={[-0.5, 6.5, 0]}>
					<Text
						fontSize={0.42}
						font="fonts/Gilroy-ExtraBold.ttf"
						textAlign="center"
					>
						Marine
						<meshStandardMaterial color="red" />
					</Text>
				</Billboard>

				<group position={[-0.715, 0, 0.014]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ship_light_8angles_1.geometry}
						material={materials.wood}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ship_light_8angles_2.geometry}
						material={materials.woodDark}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ship_light_8angles_3.geometry}
						material={materials.iron}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ship_light_8angles_4.geometry}
						material={materials.window}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ship_light_8angles_5.geometry}
						material={materials.textile}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ship_light_8angles_6.geometry}
						material={materials._defaultMat}
					/>
					<group position={[0, 1.437, -3.616]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_front_1_1.geometry}
							material={materials.iron}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_front_1_2.geometry}
							material={materials.wood}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_front_1_3.geometry}
							material={materials.iron}
							position={[0, 0.278, -0.067]}
							rotation={[0.073, 0, 0]}
						/>
					</group>
					<group
						position={[-0.76, 1.277, -1.681]}
						rotation={[0, Math.PI / 2, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_left_1_1.geometry}
							material={materials.iron}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_left_1_2.geometry}
							material={materials.wood}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_left_1_3.geometry}
							material={materials.iron}
							position={[0, 0.444, -0.067]}
							rotation={[0.093, 0, 0]}
						/>
						<group position={[-0.217, 0.128, 0.262]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
						<group
							position={[0.217, 0.128, 0.262]}
							rotation={[Math.PI, 0, Math.PI]}
						>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
						<group position={[-0.217, 0.128, -0.197]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
						<group
							position={[0.217, 0.128, -0.197]}
							rotation={[Math.PI, 0, Math.PI]}
						>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
					</group>
					<group
						position={[0.76, 1.277, -1.681]}
						rotation={[0, -Math.PI / 2, 0]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_left_1_1.geometry}
							material={materials.iron}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_left_1_2.geometry}
							material={materials.wood}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.cannon_right_1_1.geometry}
							material={materials.iron}
							position={[0, 0.444, -0.067]}
							rotation={[0.093, 0, 0]}
						/>
						<group position={[-0.217, 0.128, 0.262]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
						<group
							position={[0.217, 0.128, 0.262]}
							rotation={[Math.PI, 0, Math.PI]}
						>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
						<group position={[-0.217, 0.128, -0.197]}>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
						<group
							position={[0.217, 0.128, -0.197]}
							rotation={[Math.PI, 0, Math.PI]}
						>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_8.geometry}
								material={materials.iron}
							/>
							<mesh
								castShadow
								receiveShadow
								geometry={nodes.cannon_left_1_9.geometry}
								material={materials.wood}
							/>
						</group>
					</group>
					<group position={[1.354, 3.034, 1.864]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.sail_back_1_1.geometry}
							material={materials.textile}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.sail_back_1_2.geometry}
							material={materials.wood}
						/>
					</group>
					<group position={[1.354, 1.604, -3.201]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.sail_front_1_1.geometry}
							material={materials.textile}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.sail_front_1_2.geometry}
							material={materials.wood}
						/>
					</group>
					<group position={[1.354, 1.604, -1.546]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.sail_middle_1_1.geometry}
							material={materials.textile}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.sail_middle_1_2.geometry}
							material={materials.wood}
						/>
					</group>
					<group position={[0, 2.776, 1.051]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.steering_1_1.geometry}
							material={materials.wood}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.steering_1_2.geometry}
							material={materials.iron}
						/>
					</group>
				</group>
			</Float>
		</group>
	);
};

useGLTF.preload("/models/ship_light.gltf");
